name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # 监控主分支上的变动

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Node.js 版本，可以根据需要调整

      - name: Install dependencies
        run: |
          npm install pnpm -g
          pnpm install

      - name: Build Next.js
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Next.js 静态输出的目录